# generated by mBlock5 for CyberPi
# codes make you happy
# =============================================================
#  CyberPi + AI Camera 2.0  ボール追従プログラム（物体認識版）
# =============================================================
#  ・AI Camera 2.0 の「物体認識」で、学習させた赤ボール／青ボールを検知
#    （ボールとして学習した物だけに反応するので、名前のない色のかたまりには動かない）
#  ・赤ボール -> 追従し、距離を約10cmに保つ
#  ・青ボール -> そっぽを向く（反対方向へ旋回）
#  ・なし     -> 停止（ボールを見つけるまでは停止のまま待機）
#
#  ＜事前準備（AI Camera 2.0 側）＞
#   物体認識モードにして、ボールを2種類“別々の物体”として学習させる:
#     ・赤ボールを学習 -> 名前を RED_BALL と一致させる
#     ・青ボールを学習 -> 名前を BLUE_BALL と一致させる
#   ※ カメラ本体を「物体認識モード」に切り替えておくこと
# =============================================================

import event, time, cyberpi, mbuild, mbot2

# -------------------------------------------------------------
#  学習させたボールの名前（AI Camera 側の学習名と必ず一致させる）
# -------------------------------------------------------------
RED_BALL = "RedBall"        # 赤ボールの学習名
BLUE_BALL = "BlueBall"      # 青ボールの学習名

# -------------------------------------------------------------
#  調整用パラメータ（実機に合わせてキャリブレーション）
# -------------------------------------------------------------
FRAME_CENTER_X = 320       # 画面中心X（実機のXの範囲を見て調整）
X_TOLERANCE = 10          # 中心とみなす左右の許容差

TARGET_WIDTH = 180         # 約10cmのときのボールの幅(px)。要キャリブレーション
WIDTH_TOLERANCE = 15      # この範囲内なら「ちょうど良い距離」とみなす

KP_TURN = 0.04            # 左右ずれ -> 旋回量への係数
KP_DRIVE = 0.4           # 距離ずれ -> 前後速度への係数

MAX_SPEED = 80           # 前後速度の上限
SPIN_SPEED = 30          # 青のとき背を向ける旋回スピード
LOOP_INTERVAL = 0.05     # 制御周期（秒）


def clamp(value, low, high):
    if value < low:
        return low
    if value > high:
        return high
    return value


# -------------------------------------------------------------
#  学習させた名前のボールを1つ読み取る
#    戻り値: (x, w) / 見つからなければ None
#    （未検出のとき get_object_x は負の値 -99999 を返す）
#
#  ★幅(サイズ)の取得 get_object_w は要確認★
#    もしこの行でエラーが出る場合は、mBlock で「物体の幅／サイズを取得」
#    ブロックを1つ置いて生成された関数名に置き換えてください。
# -------------------------------------------------------------
def read_ball(name):
    x = mbuild.ai_camera.get_object_x(name, 1)
    if x < 0:                       # 負の値 = 未検出
        return None
    w = mbuild.ai_camera.get_object_w(name, 1)
    if w < 0:
        return None
    return (x, w)


# -------------------------------------------------------------
#  赤ボールに追従して距離10cmを保つ
# -------------------------------------------------------------
def follow_red(x, w):
    # 左右のずれ（プラス=ボールが右）-> 旋回成分
    error_x = x - FRAME_CENTER_X
    if abs(error_x) <= X_TOLERANCE:
        turn = 0
    else:
        turn = KP_TURN * error_x

    # 距離のずれ。w が小さい=遠い=前進、w が大きい=近い=後退
    width_error = TARGET_WIDTH - w
    if abs(width_error) <= WIDTH_TOLERANCE:
        drive = 0
    else:
        drive = KP_DRIVE * width_error

    drive = clamp(drive, -MAX_SPEED, MAX_SPEED)

    # mBot2 の前進は drive_speed(v, -v)（右モーターは符号反転）
    left_speed = clamp(drive + turn, -MAX_SPEED, MAX_SPEED)
    right_speed = clamp(turn - drive, -MAX_SPEED, MAX_SPEED)
    mbot2.drive_speed(left_speed, right_speed)


# -------------------------------------------------------------
#  青ボールからそっぽを向く
# -------------------------------------------------------------
def turn_away_from_blue(x):
    # 追従とは逆向きにその場旋回して背を向ける
    if x >= FRAME_CENTER_X:
        # ボールが右 -> 左へ回って背を向ける
        mbot2.drive_speed(-SPIN_SPEED, -SPIN_SPEED)
    else:
        # ボールが左 -> 右へ回って背を向ける
        mbot2.drive_speed(SPIN_SPEED, SPIN_SPEED)


def stop():
    mbot2.drive_speed(0, 0)


def show_state(text, r, g, b):
    cyberpi.led.on(r, g, b)
    cyberpi.display.show_label(text, 16, "center", index=0)


# -------------------------------------------------------------
#  メインループ
# -------------------------------------------------------------
@event.start
def on_start():
    # ボールを見つけるまでは停止して待機
    stop()
    cyberpi.led.off()
    cyberpi.display.show_label("NO BALL", 16, "center", index=0)

    while True:
        red = read_ball(RED_BALL)
        if red is not None:
            show_state("RED BALL: FOLLOW", 255, 0, 0)
            follow_red(red[0], red[1])
        else:
            blue = read_ball(BLUE_BALL)
            if blue is not None:
                show_state("BLUE BALL: TURN AWAY", 0, 0, 255)
                turn_away_from_blue(blue[0])
            else:
                stop()
                cyberpi.led.off()
                cyberpi.display.show_label("NO BALL", 16, "center", index=0)

        time.sleep(LOOP_INTERVAL)
